replicaCount: 1

image:
  repository: avian19/go-port
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: dev

backendReplicaCount: 1
backendImage:
  repository: avian19/go-backend
  tag: dev
