replicaCount: 2

image:
  repository: avian19/go-port
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: staging

backendImage:
  repository: yourdocker/go-backend
  tag: staging
