replicaCount: 1

image:
  repository: avian19/go-port
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "25672082258"

backendImage:
  repository: yourdocker/go-backend
  tag: "25672082258"
