apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-backend
  namespace: {{ .Release.Namespace }}
  labels:
    role: go-backend
    env: dev
spec:
  replicas: {{ .Values.backendReplicaCount }}

  selector:
    matchLabels:
      role: go-backend
  template:
    metadata:
      labels:
        role: go-backend
    spec:
      containers:
        - name: go-backend
          image: "{{ .Values.backendImage.repository }}:{{ .Values.backendImage.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
