name: Go App CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/hand/ci
    paths:
      - "app/**"
      - ".github/workflows/go-app.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/go-app.yaml"

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: app/go.mod

      - name: Check Go version
        run: go version

      - name: Download dependencies
        run: go mod download

      - name: Format check
        run: |
          files=$(gofmt -l .)
          if [ -n "$files" ]; then
          echo "These files are not gofmt formatted:"
          echo "$files"
          exit 1
          fi
          
      - name: Run tests
        run: go test ./...

      - name: Build application
        run: go build -v ./...

      - name: Build Docker image
        run: docker build -t go-port:ci .